config/routes.rb
FurryHelpster::Application.routes.draw do
  resources :products, :only => [:index, :show]
  resources :versions, :only => [:show]
  resources :doc_groups, :only => [:show]
  resources :documents, :only => [:show]

  namespace :admin do
    resources :doc_groups
    resources :documents
    resources :versions
    resources :products
  end

  root :to => 'welcome#index'
end

app/models/version.rb
class Version < ActiveRecord::Base
  belongs_to :product
  has_many :doc_groups

  attr_accessible :name, :private, :product_id, :state

  scope :all_public, where(:private => false)

  def friendly_name
    "#{self.product.name} v#{self.name}"
  end

  def head_groups
    self.doc_groups.where(:parent_id => nil).includes(:children)
  end
end

app/controllers/admin/versions_controller.rb
class Admin::VersionsController < Admin::ApplicationController
  # GET /versions
  # GET /versions.json
  def index
    @versions = Version.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @versions }
    end
  end

  # GET /versions/1
  # GET /versions/1.json
  def show
    @version = Version.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @version }
    end
  end

  # GET /versions/new
  # GET /versions/new.json
  def new
    @version = Version.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @version }
    end
  end

  # GET /versions/1/edit
  def edit
    @version = Version.find(params[:id])
  end

  # POST /versions
  # POST /versions.json
  def create
    @version = Version.new(params[:version])

    respond_to do |format|
      if @version.save
        format.html { redirect_to admin_version_url(@version), notice: 'Version was successfully created.' }
        format.json { render json: @version, status: :created, location: @version }
      else
        format.html { render action: "new" }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /versions/1
  # PUT /versions/1.json
  def update
    @version = Version.find(params[:id])

    respond_to do |format|
      if @version.update_attributes(params[:version])
        format.html { redirect_to admin_version_url(@version), notice: 'Version was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /versions/1
  # DELETE /versions/1.json
  def destroy
    @version = Version.find(params[:id])
    @version.destroy

    respond_to do |format|
      format.html { redirect_to versions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  def show
    @version = Version.find(params[:id])
  end
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/admin/versions/_form.html.erb
<%= form_for([:admin, @version]) do |f| %>
  <% if @version.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@version.errors.count, "error") %> prohibited this version from being saved:</h2>

      <ul>
      <% @version.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= collection_select(:version, :product_id, Product.all, :id, :name, { :prompt => 'Select a product' }) %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :private %><br />
    <%= f.check_box :private %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/versions/edit.html.erb
<h1>Editing version</h1>

<%= render 'form' %>

<%= link_to 'Show', @version %> |
<%= link_to 'Back', admin_versions_path %>

app/views/admin/versions/index.html.erb
<h1>Listing versions</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Name</th>
    <th>State</th>
    <th>Private</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @versions.each do |version| %>
  <tr>
    <td><%= version.product.name %></td>
    <td><%= version.name %></td>
    <td><%= version.state %></td>
    <td><%= version.private %></td>
    <td><%= link_to 'Show', version %></td>
    <td><%= link_to 'Edit', edit_admin_version_path(version) %></td>
    <td><%= link_to 'Destroy', version, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Version', new_admin_version_path %>

app/views/admin/versions/new.html.erb
<h1>New version</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_versions_path %>

app/views/admin/versions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @version.name %>
</p>

<p>
  <b>State:</b>
  <%= @version.state %>
</p>

<p>
  <b>Private:</b>
  <%= @version.private %>
</p>


<%= link_to 'Edit', edit_admin_version_path(@version) %> |
<%= link_to 'Back', admin_versions_path %>