config/routes.rb
FurryHelpster::Application.routes.draw do
  resources :products, :only => [:index, :show]
  resources :versions, :only => [:show]
  resources :doc_groups, :only => [:show]
  resources :documents, :only => [:show]

  namespace :admin do
    resources :doc_groups
    resources :documents
    resources :versions
    resources :products
  end

  root :to => 'welcome#index'
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :doc_group

  attr_accessible :content, :doc_group_id, :name, :private

  scope :all_public, where(:private => false)
end

app/controllers/admin/documents_controller.rb
class Admin::DocumentsController < Admin::ApplicationController
  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @documents }
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(params[:document])

    respond_to do |format|
      if @document.save
        format.html { redirect_to admin_document_url(@document), notice: 'Document was successfully created.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to admin_document_url(@document), notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def show
    @document = Document.find(params[:id])
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
  #noinspection RubyClassVariableUsageInspection
  def markdown(text)
    options ||= [:underline => true, :highlight => true, :space_after_headers => true,
                 :autolink => true, :strikethrough => true]
    @@renderer ||= Redcarpet::Render::HTML.new(:with_toc_data => true, :prettify => true)
    @@markdown ||= Redcarpet::Markdown.new(@@renderer, *options)
    @@markdown.render(text).html_safe
  end
end

app/views/admin/documents/_form.html.erb
<%= form_for([:admin, @document], :html => { :class => 'form-horizontal' }) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :doc_group_id, :class => 'control-label' %>

    <div class="controls">
      <%= collection_select(:document, :doc_group_id, DocGroup.all, :id, :friendly_name, { :prompt => 'Select a version' }, { :class => 'span6' }) %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>

    <div class="controls">
      <%= f.text_field :name, :class => 'span4' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>

    <div class="controls">
      <%= f.text_area :content, { :rows => 10, :class => 'span8' } %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :private, :class => 'control-label' %>

    <div class="controls">
      <%= f.check_box :private %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/documents/edit.html.erb
<% provide :title, t('.html_title', :doc => @document.name) %>

<h1 class="page-header"><%= t('.title', :doc => @document.name) %></h1>

<%= render 'form' %>

<%= link_to t('.show'), @document %> |
<%= link_to t('.back'), admin_documents_path %>

app/views/admin/documents/index.html.erb
<% provide :title, t('.html_title') %>

<h1 class="page-header"><%= t('.title') %></h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th><%= t('.group') %></th>
      <th><%= t('.name') %></th>
      <th><%= t('.content') %></th>
      <th><%= t('.private') %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

<% @documents.each do |document| %>
  <tr>
    <td><%= document.doc_group.friendly_name %></td>
    <td><%= document.name %></td>
    <td><%= truncate(document.content) %></td>
    <td><%= document.private %></td>
    <td><%= link_to t('.show'), document %></td>
    <td><%= link_to t('.edit'), edit_admin_document_path(document) %></td>
    <td><%= link_to t('.destroy'), document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t('.new'), new_admin_document_path %>

app/views/admin/documents/new.html.erb
<% provide :title, t('.html_title') %>

<h1 class="page-header"><%= t('.title') %></h1>

<%= render 'form' %>

<%= link_to t('.back'), admin_documents_path %>

app/views/admin/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @document.name %>
</p>

<p>
  <b>Content:</b>
  <%= @document.content %>
</p>

<p>
  <b>Private:</b>
  <%= @document.private %>
</p>


<%= link_to 'Edit', edit_admin_document_path(@document) %> |
<%= link_to 'Back', admin_documents_path %>