config/routes.rb
FurryHelpster::Application.routes.draw do
  resources :products, :only => [:index, :show]
  resources :versions, :only => [:show]
  resources :doc_groups, :only => [:show]
  resources :documents, :only => [:show]

  namespace :admin do
    resources :doc_groups
    resources :documents
    resources :versions
    resources :products
  end

  root :to => 'welcome#index'
end

app/models/doc_group.rb
class DocGroup < ActiveRecord::Base
  belongs_to :version
  belongs_to :primary_doc, :class_name => 'Document'

  has_many :documents

  has_many :children, :class_name => 'DocGroup', :foreign_key => 'parent_id'
  belongs_to :parent, :class_name => 'DocGroup'

  attr_accessible :name, :parent_id, :primary_doc_id, :private, :version_id

  scope :all_public, where(:private => false)

  def deep_contains(group)
    self.children.include?(group)

    # eventually, someday, recurse on children
  end

  def is_or_has(group)
    return false if group == nil
    return false if group == self.parent # quick false, reduces queries (yes, I profiled)

    self == group || self.deep_contains(group)
  end

  def friendly_name
    "#{self.version.product.name} v#{self.version.name} - #{self.name}"
  end
end

app/controllers/admin/doc_groups_controller.rb
class Admin::DocGroupsController < Admin::ApplicationController
  # GET /doc_groups
  # GET /doc_groups.json
  def index
    @doc_groups = DocGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @doc_groups }
    end
  end

  # GET /doc_groups/1
  # GET /doc_groups/1.json
  def show
    @doc_group = DocGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @doc_group }
    end
  end

  # GET /doc_groups/new
  # GET /doc_groups/new.json
  def new
    @doc_group = DocGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @doc_group }
    end
  end

  # GET /doc_groups/1/edit
  def edit
    @doc_group = DocGroup.find(params[:id])
  end

  # POST /doc_groups
  # POST /doc_groups.json
  def create
    @doc_group = DocGroup.new(params[:doc_group])

    respond_to do |format|
      if @doc_group.save
        format.html { redirect_to admin_doc_group_url(@doc_group), notice: 'Doc group was successfully created.' }
        format.json { render json: @doc_group, status: :created, location: @doc_group }
      else
        format.html { render action: "new" }
        format.json { render json: @doc_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /doc_groups/1
  # PUT /doc_groups/1.json
  def update
    @doc_group = DocGroup.find(params[:id])

    respond_to do |format|
      if @doc_group.update_attributes(params[:doc_group])
        format.html { redirect_to admin_doc_group_url(@doc_group), notice: 'Doc group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @doc_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doc_groups/1
  # DELETE /doc_groups/1.json
  def destroy
    @doc_group = DocGroup.find(params[:id])
    @doc_group.destroy

    respond_to do |format|
      format.html { redirect_to doc_groups_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/doc_groups_controller.rb
class DocGroupsController < ApplicationController
  def show
    @doc_group = DocGroup.includes(:version).find(params[:id])
  end
end

app/helpers/doc_groups_helper.rb
module DocGroupsHelper
end

app/views/admin/doc_groups/_form.html.erb
<%= form_for([:admin, @doc_group], :html => { :class => 'form-horizontal' }) do |f| %>
  <% if @doc_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doc_group.errors.count, "error") %> prohibited this doc_group from being saved:</h2>

      <ul>
      <% @doc_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :version_id, :class => 'control-label' %>

    <div class="controls">
      <%= collection_select(:doc_group, :version_id, Version.all, :id, :friendly_name) %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :parent_id, :class => 'control-label' %>

    <div class="controls">
      <%= f.number_field :parent_id %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>

    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :private, :class => 'control-label' %>

    <div class="controls">
      <%= f.check_box :private %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :primary_doc_id, :class => 'control-label' %>

    <div class="controls">
      <%= f.number_field :primary_doc_id %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/doc_groups/edit.html.erb
<% provide :title, t('.html_title', :group => @doc_group.name) %>

<h1 class="page-header"><%= t('.title', :group => @doc_group.name) %></h1>

<%= render 'form' %>

<%= link_to t('.show'), @doc_group %> |
<%= link_to t('.back'), admin_doc_groups_path %>

app/views/admin/doc_groups/index.html.erb
<% provide :title, t('.html_title') %>

<h1 class="page-header"><%= t('.title') %></h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th><%= t('.version') %></th>
      <th><%= t('.name') %></th>
      <th><%= t('.private') %></th>
      <th><%= t('.primary_doc') %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

<% @doc_groups.each do |doc_group| %>
  <tr>
    <td><%= doc_group.version.friendly_name %></td>
    <td><%= doc_group.name %></td>
    <td><%= doc_group.private %></td>
    <td><%= link_to doc_group.primary_doc.name, admin_document_path(doc_group.primary_doc) unless doc_group.primary_doc.nil? %></td>
    <td><%= link_to t('.show'), doc_group %></td>
    <td><%= link_to t('.edit'), edit_admin_doc_group_path(doc_group) %></td>
    <td><%= link_to t('.destroy'), doc_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t('.new'), new_admin_doc_group_path %>

app/views/admin/doc_groups/new.html.erb
<% provide :title, t('.html_title') %>

<h1 class="page-header"><%= t('.title') %></h1>

<%= render 'form' %>

<%= link_to t('.back'), admin_doc_groups_path %>

app/views/admin/doc_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Version:</b>
  <%= @doc_group.version.friendly_name %>
</p>

<p>
  <b>Name:</b>
  <%= @doc_group.name %>
</p>

<p>
  <b>Private:</b>
  <%= @doc_group.private %>
</p>

<p>
  <b>Primary doc:</b>
  <%= @doc_group.primary_doc_id %>
</p>


<%= link_to 'Edit', edit_admin_doc_group_path(@doc_group) %> |
<%= link_to 'Back', admin_doc_groups_path %>